services:
  web:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env.prod.db
    ports:
      - "8000:8000"
    command: sh -c "python manage.py migrate && gunicorn rosegold_v1.wsgi --bind 0.0.0.0:8000"
    depends_on:
      - db

  db:
    build: ./docker/postgres
    ports:
      - '5432:5432'
    volumes:
      - nkwazi_postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.prod.db
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_NAME: ${DATABASE_NAME}

  redis:
    image: redis:6
    ports:
      - '6379:6379'

volumes:
  nkwazi_postgres_data: