# Generated by Django 5.0.8 on 2024-09-15 15:31

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_gallerypages_remove_gallery_images_gallerypage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero_section', 2), ('gallery_section', 4), ('team_section', 7), ('featured_gallery', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('caption', 1), ('attribution', 1)]], {}), 3: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['home.GalleryPages'], 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('page', 3)]], {}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('name', 1), ('title', 1), ('description', 1)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {}), 7: ('wagtail.blocks.StructBlock', [[('members', 6)]], {})}, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='home.category'),
        ),
    ]
