# Generated by Django 5.0.8 on 2024-09-15 16:45

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_gallerydetailspage_gallery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerydetailspage',
            name='galleries',
        ),
        migrations.CreateModel(
            name='GalleriesDetailPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_details_page', to='home.gallery')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_details', to='home.gallerydetailspage')),
            ],
        ),
    ]
