# Generated by Django 5.0.8 on 2024-09-15 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_gallerydetailspage_galleries_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleriesdetailpage',
            old_name='gallery',
            new_name='picture',
        ),
    ]
