# Generated by Django 5.0.8 on 2024-09-18 17:57

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_gallery_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero_section', 2), ('gallery_section', 4), ('team_section', 7), ('featured_gallery', 9)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('caption', 1), ('attribution', 1)]], {}), 3: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['home.GalleryPages'], 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('page', 3)]], {}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('name', 1), ('title', 1), ('description', 1)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {}), 7: ('wagtail.blocks.StructBlock', [[('members', 6)]], {}), 8: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['home.GalleryDetailsPage'], 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('page', 8)]], {})}, null=True),
        ),
    ]
